apiVersion: v1
kind: Service
metadata:
  name: demo-loadbalancer
spec:
  type: LoadBalancer
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
#it will actually create loadbalance and give the common end point you can give user
#access the apply via web